const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    // Products
    addProduct: (product) => ipcRenderer.invoke('add-product', product),
    getProducts: (options) => ipcRenderer.invoke('get-products', options),
    getProductsPage: (options) => ipcRenderer.invoke('get-products-page', options),
    getProductStats: () => ipcRenderer.invoke('get-product-stats'),
    searchProducts: (options) => ipcRenderer.invoke('search-products', options),
    getLowStockSummary: () => ipcRenderer.invoke('get-low-stock-summary'),
    getNotificationSummary: () => ipcRenderer.invoke('get-notification-summary'),
    getInventoryBatches: () => ipcRenderer.invoke('get-inventory-batches'),
    updateProduct: (product) => ipcRenderer.invoke('update-product', product),
    deleteProduct: (id) => ipcRenderer.invoke('delete-product', id),
    addStock: (data) => ipcRenderer.invoke('add-stock', data),
    discardStock: (data) => ipcRenderer.invoke('discard-stock', data),
    searchProductByBarcode: (barcode) => ipcRenderer.invoke('search-barcode', barcode),
    getSuppliers: () => ipcRenderer.invoke('get-suppliers'),
    saveSupplier: (supplier) => ipcRenderer.invoke('save-supplier', supplier),
    savePurchaseInvoice: (payload) => ipcRenderer.invoke('save-purchase-invoice', payload),
    getPurchaseInvoices: () => ipcRenderer.invoke('get-purchase-invoices'),
    recordSupplierPayment: (payload) => ipcRenderer.invoke('record-supplier-payment', payload),
    getSupplierPayments: () => ipcRenderer.invoke('get-supplier-payments'),
    getProductDiscounts: () => ipcRenderer.invoke('get-product-discounts'),
    saveProductDiscount: (discount) => ipcRenderer.invoke('save-product-discount', discount),
    recordStockAdjustment: (payload) => ipcRenderer.invoke('record-stock-adjustment', payload),
    getStockAdjustments: () => ipcRenderer.invoke('get-stock-adjustments'),
    recordReturn: (payload) => ipcRenderer.invoke('record-return', payload),
    getReturns: () => ipcRenderer.invoke('get-returns'),
    saveUnitConversion: (payload) => ipcRenderer.invoke('save-unit-conversion', payload),
    getUnitConversions: () => ipcRenderer.invoke('get-unit-conversions'),
    getPriceHistory: (productId) => ipcRenderer.invoke('get-price-history', productId),
    getReorderList: () => ipcRenderer.invoke('get-reorder-list'),
    getAuditLog: () => ipcRenderer.invoke('get-audit-log'),
    savePromotion: (payload) => ipcRenderer.invoke('save-promotion', payload),
    getPromotions: () => ipcRenderer.invoke('get-promotions'),
    recordTillMovement: (payload) => ipcRenderer.invoke('record-till-movement', payload),
    getTillMovements: () => ipcRenderer.invoke('get-till-movements'),
    saveSalePayments: (payload) => ipcRenderer.invoke('save-sale-payments', payload),
    getSalePayments: (saleId) => ipcRenderer.invoke('get-sale-payments', saleId),
    voidBill: (payload) => ipcRenderer.invoke('void-bill', payload),
    getVoidBills: () => ipcRenderer.invoke('get-void-bills'),
    holdBill: (payload) => ipcRenderer.invoke('hold-bill', payload),
    getHeldBills: () => ipcRenderer.invoke('get-held-bills'),
    deleteHeldBill: (id) => ipcRenderer.invoke('delete-held-bill', id),
    saveTaxCategory: (payload) => ipcRenderer.invoke('save-tax-category', payload),
    getTaxCategories: () => ipcRenderer.invoke('get-tax-categories'),
    saveBranch: (payload) => ipcRenderer.invoke('save-branch', payload),
    getBranches: () => ipcRenderer.invoke('get-branches'),
    recordStockTransfer: (payload) => ipcRenderer.invoke('record-stock-transfer', payload),
    getStockTransfers: () => ipcRenderer.invoke('get-stock-transfers'),
    saveStockCount: (payload) => ipcRenderer.invoke('save-stock-count', payload),
    getStockCounts: () => ipcRenderer.invoke('get-stock-counts'),
    queueShelfLabel: (payload) => ipcRenderer.invoke('queue-shelf-label', payload),
    getShelfLabelQueue: () => ipcRenderer.invoke('get-shelf-label-queue'),
    saveScaleBarcodeRule: (payload) => ipcRenderer.invoke('save-scale-barcode-rule', payload),
    getScaleBarcodeRules: () => ipcRenderer.invoke('get-scale-barcode-rules'),
    deleteScaleBarcodeRule: (id) => ipcRenderer.invoke('delete-scale-barcode-rule', id),
    recordSupplierReturn: (payload) => ipcRenderer.invoke('record-supplier-return', payload),
    getSupplierReturns: () => ipcRenderer.invoke('get-supplier-returns'),
    getDeadStockReport: () => ipcRenderer.invoke('get-dead-stock-report'),
    
    // Categories
    getCategories: () => ipcRenderer.invoke('get-categories'),
    saveCategory: (category) => ipcRenderer.invoke('save-category', category),
    deleteCategory: (id) => ipcRenderer.invoke('delete-category', id),
    getTopSellingCategory: () => ipcRenderer.invoke('get-top-selling-category'),
    getCategoriesRevenue: () => ipcRenderer.invoke('get-categories-revenue'),
    getActiveProductsCount: () => ipcRenderer.invoke('get-active-products-count'),
    
    // Customers
    getCustomers: () => ipcRenderer.invoke('get-customers'),
    saveCustomer: (customer) => ipcRenderer.invoke('save-customer', customer),
    deleteCustomer: (id) => ipcRenderer.invoke('delete-customer', id),

    // Users
    getUsers: () => ipcRenderer.invoke('get-users'),
    saveUser: (user) => ipcRenderer.invoke('save-user', user),
    deleteUser: (id) => ipcRenderer.invoke('delete-user', id),
    getUserShiftHistory: (payload) => ipcRenderer.invoke('get-user-shift-history', payload),

    // Settings
    getSettings: () => ipcRenderer.invoke('get-settings'),
    saveSetting: (key, value) => ipcRenderer.invoke('save-setting', key, value),

    // Sales (à¶¶à·’à¶½à·Š)
    saveSale: (saleData) => ipcRenderer.invoke('save-sale', saleData),
    getSalesHistory: (options) => ipcRenderer.invoke('get-sales-history', options),
    getSalesPage: (options) => ipcRenderer.invoke('get-sales-page', options),
    getSaleDetails: (saleId) => ipcRenderer.invoke('get-sale-details', saleId),
    recordCreditPayment: (paymentData) => ipcRenderer.invoke('record-credit-payment', paymentData),

    // Security & Logic
    loginAuth: (creds) => ipcRenderer.invoke('login-auth', creds),
    verifyAdminPin: (pin) => ipcRenderer.invoke('verify-admin-pin', pin),
    backupDatabase: () => ipcRenderer.invoke('backup-database'),
    restoreDatabase: () => ipcRenderer.invoke('restore-database'),
    runGoogleDriveBackupNow: () => ipcRenderer.invoke('run-google-drive-backup-now'),
    getGoogleDriveBackupStatus: () => ipcRenderer.invoke('get-google-drive-backup-status'),
    getExpiredItems: () => ipcRenderer.invoke('get-expired-items'),
    // Printing
    printReceiptSilent: (options) => ipcRenderer.invoke('print-receipt-silent', options),
    getPrinters: () => ipcRenderer.invoke('get-printers'),
    exportShiftSummaryPdf: (summary) => ipcRenderer.invoke('export-shift-summary-pdf', summary),
    exportReportPdf: (payload) => ipcRenderer.invoke('export-report-pdf', payload),
    recordShiftReconciliation: (payload) => ipcRenderer.invoke('record-shift-reconciliation', payload),
    getShiftClosePreview: (payload) => ipcRenderer.invoke('get-shift-close-preview', payload),
    exportThermalReceiptPdf: (payload) => ipcRenderer.invoke('export-thermal-receipt-pdf', payload),
    generateThermalReceiptPdfAuto: (payload) => ipcRenderer.invoke('generate-thermal-receipt-pdf-auto', payload),
    printThermalReceipt: (payload) => ipcRenderer.invoke('print-thermal-receipt', payload)
});
